
CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT ukghs1q6xciwjy5iijm3w1474r1
        UNIQUE (name)
);

CREATE TABLE deployments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deployed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    environment VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    version VARCHAR(50) NOT NULL,
    application_id BIGINT NOT NULL,

    CONSTRAINT deployments_environment_check
        CHECK (environment IN ('DEV', 'STAGING', 'PRODUCTION')),

    CONSTRAINT deployments_status_check
        CHECK (status IN ('SUCCESS', 'FAILED')),

    CONSTRAINT fkmonfv0lpxi1kembtscgds0ito
        FOREIGN KEY (application_id)
        REFERENCES applications (id)
);
